/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ConsultasSQL;
import Modelo.Multa;
import Modelo.Persona;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

/**
 *
 * @author alumno
 */
public class PanelMultasIndividual extends javax.swing.JPanel {

    /**
     * Creates new form PanelMultasIndividual
     */
    int multactual = 0; //En que multa de la lista estamos
    ArrayList<Multa> listamultas = new <Multa> ArrayList(); //Lista con todas las multas del usuario
    Multa multa;    //La multa en especifico

    public PanelMultasIndividual() {
        initComponents();
        System.out.println("Abriendo multas");
        labeltitulo.setText("Multas del usuario " + Persona.getUsuario().getNombre() + " " + Persona.getUsuario().getApellido());   //Un titulo para el panel

        listamultas = ConsultasSQL.consulta.guardarMultas(Persona.getUsuario().getDni()); //Crea una lista con todas las multas del usuario

        multa = listamultas.get(multactual);    //Coge la primera multa de la lista (0)
        introducirDatos(multa); //pone los datos de la multa en los fields
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fielcodigo = new javax.swing.JTextField();
        fieldmatricula = new javax.swing.JTextField();
        fieldfecha = new javax.swing.JTextField();
        fieldvalor = new javax.swing.JTextField();
        botonretroceder = new javax.swing.JButton();
        botonavanzar = new javax.swing.JButton();
        botonprimera = new javax.swing.JButton();
        botonultima = new javax.swing.JButton();
        labeltitulo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("Código Multa:");

        jLabel3.setText("Fecha Multa:");

        jLabel4.setText("Matrícula coche:");

        jLabel5.setText("Valor Multa:");

        fielcodigo.setText("jTextField1");

        fieldmatricula.setText("jTextField1");

        fieldfecha.setText("jTextField1");

        fieldvalor.setText("jTextField1");

        botonretroceder.setText("Retroceder");
        botonretroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonretrocederActionPerformed(evt);
            }
        });

        botonavanzar.setText("Avanzar");
        botonavanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonavanzarActionPerformed(evt);
            }
        });

        botonprimera.setText("Primera");
        botonprimera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonprimeraActionPerformed(evt);
            }
        });

        botonultima.setText("Ultima");
        botonultima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonultimaActionPerformed(evt);
            }
        });

        labeltitulo.setText("Multas propietario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonprimera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonultima))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonretroceder)
                                .addGap(98, 98, 98)
                                .addComponent(botonavanzar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fielcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(labeltitulo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(fielcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonretroceder)
                    .addComponent(botonavanzar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonprimera)
                    .addComponent(botonultima))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //Siguiente multa
    private void botonavanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonavanzarActionPerformed
        multactual++;
        multa = listamultas.get(multactual);
        introducirDatos(multa);
    }//GEN-LAST:event_botonavanzarActionPerformed

    //anterior multa
    private void botonretrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonretrocederActionPerformed
        multactual--;
        multa = listamultas.get(multactual);
        introducirDatos(multa);
    }//GEN-LAST:event_botonretrocederActionPerformed

    //primera multa
    private void botonprimeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonprimeraActionPerformed
        multactual=0;
        multa = listamultas.get(multactual);
        introducirDatos(multa);
    }//GEN-LAST:event_botonprimeraActionPerformed

    //ultima multa
    private void botonultimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonultimaActionPerformed
        multactual=listamultas.size()-1;
        multa = listamultas.get(multactual);
        introducirDatos(multa);
    }//GEN-LAST:event_botonultimaActionPerformed
    
    //mete los datos de la multa pasada como parametro en los fields y comprueba si la multa es la ultima o la primera
    public void introducirDatos(Multa multa) {
        fielcodigo.setText(Integer.toString(multa.getCodigo()));
        fieldmatricula.setText(multa.getCoche());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/M/yyyy");
        String dateformatted = sdf.format(multa.getFecha().getTime());
        fieldfecha.setText(dateformatted);
        fieldvalor.setText(Float.toString(multa.getCoste()));

        comprobarBotones(); //Comprueba si es la primera o la ultima

    }

    public void comprobarBotones() {
        if (multactual == 0) {
            botonretroceder.setEnabled(false);
            botonprimera.setEnabled(false);
        } else {
            botonretroceder.setEnabled(true);
            botonprimera.setEnabled(true);
        }

        if (multactual == listamultas.size() - 1) {
            botonavanzar.setEnabled(false);
            botonultima.setEnabled(false);
        } else {
            botonavanzar.setEnabled(true);
            botonultima.setEnabled(true);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonavanzar;
    private javax.swing.JButton botonprimera;
    private javax.swing.JButton botonretroceder;
    private javax.swing.JButton botonultima;
    private javax.swing.JTextField fielcodigo;
    private javax.swing.JTextField fieldfecha;
    private javax.swing.JTextField fieldmatricula;
    private javax.swing.JTextField fieldvalor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labeltitulo;
    // End of variables declaration//GEN-END:variables
}
